spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://amazonheatdb.cczulapjuexr.eu-west-2.rds.amazonaws.com:3306/heatDB
    username: admin
    password: d76cf6cc9bfcd880395ddea39468bbe327a7f6bd
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000